### ISSUE TITLE
bruh

### ISSUE THREAD

**Issue by LankyBox01** [AutoUOC/site-v2#1]
you really still workin on this?

**Comment by LankyBox01** [comment]
I'm lankybox01 btw, now i am ["fully educated"](https://github.com/AutoUOC/site/pull/21#issuecomment-681909157) about express with a lot of experience w/ back-end developing.

**Comment by GrahamSH-LLK** [comment]
> I'm lankybox01 btw, now i am ["fully educated"](https://github.com/AutoUOC/site/pull/21#issuecomment-681909157) about express with a lot of experience w/ back-end developing.

Fun fact: v2 doesn't use express

**Comment by LankyBox01** [comment]
> > I'm lankybox01 btw, now i am ["fully educated"](https://github.com/AutoUOC/site/pull/21#issuecomment-681909157) about express with a lot of experience w/ back-end developing.
> 
> Fun fact: v2 doesn't use express

Oh mother fu-

**Comment by bremea** [comment]
express in prod is dumb

we're using fasitify, it's much better

**Comment by LankyBox01** [comment]
use reaaaaaaaaaaaaaaaaaaaact

**Comment by bremea** [comment]
> use reaaaaaaaaaaaaaaaaaaaact

See [https://scratch.mit.edu/discuss/topic/528396/?page=1#post-5425002](https://scratch.mit.edu/discuss/topic/528396/?page=1#post-5425002)

**Comment by LankyBox01** [comment]
> > use reaaaaaaaaaaaaaaaaaaaact
> 
> See https://scratch.mit.edu/discuss/topic/528396/?page=1#post-5425002

ok
